dist: trusty
language: java
jdk:
  - openjdk8
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
addons:
  sonarcloud:
    organization: "charlemaznable"
script:
  - mvn clean verify sonar:sonar -Dsonar.projectKey=CharLemAznable_varys-java-driver
after_success:
  - bash <(curl -s https://codecov.io/bash)
